"""CX50 HC Question Bank
Structured MCQ items for every HC in the CX50 course.
Each question contains: difficulty, stem, options, correct answer flag, and explanation.
"""

CX50_HC_QUESTIONS = {
    "#complexcausality": [
        {
            "difficulty": "easy",
            "question": "A hospital implements a hand-washing campaign, but infection rates do not drop because antibiotics remain overused. What does this illustrate about causality in complex systems?",
            "options": [
                {"label": "A", "text": "There is always a single sufficient cause", "is_correct": False},
                {"label": "B", "text": "This is just a random correlation", "is_correct": False},
                {"label": "C", "text": "Multiple interacting causal factors offset each other", "is_correct": True},
                {"label": "D", "text": "It is a linear cause-and-effect chain", "is_correct": False}
            ],
            "explanation": "Hand-washing is only one factor; antibiotic overuse interacts with it, showing complex causality where multiple causes combine." 
        },
        {
            "difficulty": "easy",
            "question": "Which scenario best demonstrates complex causality instead of simple causation?",
            "options": [
                {"label": "A", "text": "Flipping a light switch turns on the light", "is_correct": False},
                {"label": "B", "text": "Adding salt to water lowers the freezing point", "is_correct": False},
                {"label": "C", "text": "A new highway reduces downtown traffic but increases suburban sprawl, which then increases overall congestion", "is_correct": True},
                {"label": "D", "text": "Heating water causes it to boil", "is_correct": False}
            ],
            "explanation": "The highway triggers a cascade of interacting effects—an archetypal example of complex causality." 
        },
        {
            "difficulty": "medium",
            "question": "A country subsidizes solar panels, but coal consumption rises because cheap solar power enables factories to expand production. Which principle of complex causality was ignored?",
            "options": [
                {"label": "A", "text": "Temporal correlation equals causation", "is_correct": False},
                {"label": "B", "text": "Unintended consequences emerge from interacting variables", "is_correct": True},
                {"label": "C", "text": "Emergent properties dominate", "is_correct": False},
                {"label": "D", "text": "Networks of influence explain everything", "is_correct": False}
            ],
            "explanation": "Analysts ignored the indirect causal chain in which cheaper energy spurs industrial expansion, raising coal demand." 
        },
        {
            "difficulty": "medium",
            "question": "A school reduces class sizes to improve test scores. Scores rise briefly but plateau because teacher quality varies and curriculum updates lag. What does this reveal?",
            "options": [
                {"label": "A", "text": "Class size is irrelevant", "is_correct": False},
                {"label": "B", "text": "Multiple causal factors interact to drive outcomes", "is_correct": True},
                {"label": "C", "text": "The intervention failed completely", "is_correct": False},
                {"label": "D", "text": "Test scores are random", "is_correct": False}
            ],
            "explanation": "Class size matters only in combination with other variables, illustrating interacting causal pathways." 
        },
        {
            "difficulty": "medium",
            "question": "After a city bans plastic bags, litter decreases but reusable bag sales spike, increasing water use for washing. Which HC best frames the trade-offs?",
            "options": [
                {"label": "A", "text": "#complexcausality", "is_correct": True},
                {"label": "B", "text": "#emergentproperties", "is_correct": False},
                {"label": "C", "text": "#networks", "is_correct": False},
                {"label": "D", "text": "#systemmapping", "is_correct": False}
            ],
            "explanation": "The intervention triggered interacting causal chains with competing effects that must be weighed together." 
        },
        {
            "difficulty": "hard",
            "question": "A drought prompts farmers to pump more groundwater, lowering the water table, increasing pumping costs, forcing some farms to close, reducing food supply, and raising prices that incentivize other regions to intensify farming. Which dynamic is most evident?",
            "options": [
                {"label": "A", "text": "A simple linear chain", "is_correct": False},
                {"label": "B", "text": "Reinforcing feedback loops across multiple causal pathways", "is_correct": True},
                {"label": "C", "text": "Random environmental variation", "is_correct": False},
                {"label": "D", "text": "A single root cause", "is_correct": False}
            ],
            "explanation": "Each effect becomes the next cause, illustrating reinforcing loops within complex causality." 
        },
        {
            "difficulty": "hard",
            "question": "A public health campaign reduces smoking rates by 10%, but lung cancer rates remain unchanged for 20 years due to latency. Policymakers declare failure. What causal complexity did they overlook?",
            "options": [
                {"label": "A", "text": "Spatial lag effects", "is_correct": False},
                {"label": "B", "text": "Temporal lag between intervention and measurable outcome", "is_correct": True},
                {"label": "C", "text": "Network effects", "is_correct": False},
                {"label": "D", "text": "Emergent thresholds", "is_correct": False}
            ],
            "explanation": "Complex causal chains often include time delays; outcomes can be caused correctly but appear later." 
        },
        {
            "difficulty": "hard",
            "question": "A financial regulation reduces risky lending at large banks but pushes risk into unregulated shadow banks, which trigger a crisis later. Which combination explains the failure?",
            "options": [
                {"label": "A", "text": "#complexcausality plus incomplete system mapping", "is_correct": True},
                {"label": "B", "text": "#emergentproperties plus network hubs", "is_correct": False},
                {"label": "C", "text": "Linear causality plus deduction", "is_correct": False},
                {"label": "D", "text": "Simple feedback plus constraints", "is_correct": False}
            ],
            "explanation": "Ignoring interactions outside the regulated sector caused risk migration—a hallmark of complex causality." 
        }
    ],
    "#emergentproperties": [
        {"difficulty": "easy", "question": "What is an emergent property?", "options": [{"label": "A", "text": "A feature predictable by examining parts in isolation", "is_correct": False}, {"label": "B", "text": "A system-level feature arising from interactions among parts", "is_correct": True}, {"label": "C", "text": "A purely random fluctuation", "is_correct": False}, {"label": "D", "text": "A property inherited from the largest component", "is_correct": False}], "explanation": "Emergence describes properties that appear only when components interact."},
        {"difficulty": "easy", "question": "Which example best demonstrates an emergent property?", "options": [{"label": "A", "text": "A car's speed depends on engine power", "is_correct": False}, {"label": "B", "text": "Individual drivers unintentionally create traffic jams", "is_correct": True}, {"label": "C", "text": "Water freezes at 0°C", "is_correct": False}, {"label": "D", "text": "A tower's height is the sum of its floors", "is_correct": False}], "explanation": "Traffic waves emerge from driver interactions, not from any single driver's intent."},
        {"difficulty": "medium", "question": "Ant colonies optimize foraging routes even though each ant follows simple local rules. Why is efficiency an emergent property?", "options": [{"label": "A", "text": "A single ant directs the colony", "is_correct": False}, {"label": "B", "text": "Colony-level efficiency arises from interactions, not individual intelligence", "is_correct": True}, {"label": "C", "text": "Ants are genetically smarter", "is_correct": False}, {"label": "D", "text": "The queen issues optimization orders", "is_correct": False}], "explanation": "Simple behavioral rules combine to produce intelligent colony behavior—an emergent outcome."},
        {"difficulty": "medium", "question": "A classroom of equally skilled students self-organizes into study groups. One group vastly outperforms the rest. What is emergent here?", "options": [{"label": "A", "text": "Individual intelligence", "is_correct": False}, {"label": "B", "text": "Group-level norms and collaboration dynamics", "is_correct": True}, {"label": "C", "text": "Teacher favoritism", "is_correct": False}, {"label": "D", "text": "Random luck", "is_correct": False}], "explanation": "The group's performance cannot be reduced to individual traits; it emerges from interaction patterns."},
        {"difficulty": "medium", "question": "A social media platform adds a 'like' button. Over time, viral content, echo chambers, and polarization emerge, none of which were designed. Which HC captures these outcomes?", "options": [{"label": "A", "text": "#emergentproperties", "is_correct": True}, {"label": "B", "text": "#complexcausality", "is_correct": False}, {"label": "C", "text": "#levelsofanalysis", "is_correct": False}, {"label": "D", "text": "#systemmapping", "is_correct": False}], "explanation": "Platform-level dynamics emerged from simple user interactions and feedback loops."},
        {"difficulty": "hard", "question": "Housing prices in a neighborhood spike once a critical number of high-income residents move in, triggering gentrification. Which two concepts explain this threshold effect?", "options": [{"label": "A", "text": "Linear aggregation and random walk", "is_correct": False}, {"label": "B", "text": "Emergent properties and critical points", "is_correct": True}, {"label": "C", "text": "Network hubs and deduction", "is_correct": False}, {"label": "D", "text": "Simple causality and constraints", "is_correct": False}], "explanation": "A tipping point creates an emergent state (gentrification) once a threshold is crossed."},
        {"difficulty": "hard", "question": "A flock of birds forms intricate patterns governed by three simple rules per bird. Why is this emergence, not aggregation?", "options": [{"label": "A", "text": "The pattern is just the sum of individual flights", "is_correct": False}, {"label": "B", "text": "Collective shapes arise that no single bird encodes", "is_correct": True}, {"label": "C", "text": "The lead bird directs the flock", "is_correct": False}, {"label": "D", "text": "It is random variation", "is_correct": False}], "explanation": "Higher-order patterns are generated by local interactions without explicit global control."},
        {"difficulty": "hard", "question": "A city planner adds bike lanes expecting more cycling. Initially car traffic slows, buses delay, commuters switch modes, and the system stabilizes at a new equilibrium. Which HCs together explain this?", "options": [{"label": "A", "text": "#emergentproperties and #systemdynamics", "is_correct": True}, {"label": "B", "text": "#networks and #complexcausality", "is_correct": False}, {"label": "C", "text": "#levelsofanalysis and #systemmapping", "is_correct": False}, {"label": "D", "text": "Linear causality and constraints", "is_correct": False}], "explanation": "A new stable state (emergent equilibrium) forms through feedback loops captured by system dynamics."}
    ],
    "#levelsofanalysis": [
        {"difficulty": "easy", "question": "What does 'levels of analysis' mean in complex systems work?", "options": [{"label": "A", "text": "Focusing only on the largest scale", "is_correct": False}, {"label": "B", "text": "Integrating explanations across micro, meso, and macro levels", "is_correct": True}, {"label": "C", "text": "Ignoring individual components", "is_correct": False}, {"label": "D", "text": "Using statistical aggregates only", "is_correct": False}], "explanation": "Levels of analysis requires linking individual, group, and systemic perspectives."},
        {"difficulty": "easy", "question": "Which research design demonstrates multi-level analysis?", "options": [{"label": "A", "text": "Studying only individual neurons", "is_correct": False}, {"label": "B", "text": "Analyzing only national economies", "is_correct": False}, {"label": "C", "text": "Linking consumer purchases, neighborhood markets, and national inflation", "is_correct": True}, {"label": "D", "text": "Surveying random individuals", "is_correct": False}], "explanation": "Connecting micro, meso, and macro factors is central to the HC."},
        {"difficulty": "medium", "question": "Student stress is influenced by personal habits (micro), peer norms (meso), and grading policy (macro). Why is this multi-level?", "options": [{"label": "A", "text": "It only examines personal habits", "is_correct": False}, {"label": "B", "text": "It connects individual, group, and institutional levels", "is_correct": True}, {"label": "C", "text": "It avoids statistics", "is_correct": False}, {"label": "D", "text": "It focuses on one survey question", "is_correct": False}], "explanation": "The study accounts for how factors at different levels interact."},
        {"difficulty": "medium", "question": "Researchers study obesity through metabolic rates (biological), food marketing (social), and agricultural subsidies (policy). Which HC guides this approach?", "options": [{"label": "A", "text": "#complexcausality", "is_correct": False}, {"label": "B", "text": "#levelsofanalysis", "is_correct": True}, {"label": "C", "text": "#emergentproperties", "is_correct": False}, {"label": "D", "text": "#networks", "is_correct": False}], "explanation": "Combining biological, social, and policy layers exemplifies this HC."},
        {"difficulty": "medium", "question": "A company analyzes turnover via job satisfaction (micro), manager quality (meso), and industry wages (macro). Why is this better than micro-only analysis?", "options": [{"label": "A", "text": "It captures cross-level interactions micro-only studies miss", "is_correct": True}, {"label": "B", "text": "It is easier to measure", "is_correct": False}, {"label": "C", "text": "It ignores individual differences", "is_correct": False}, {"label": "D", "text": "It is cheaper", "is_correct": False}], "explanation": "Turnover stems from interactions across levels; a single-level model would miss these."},
        {"difficulty": "hard", "question": "A health intervention targets masks (individual), social pressure (community), and policy mandates (national). Evaluations focus only on individual compliance. What's the analytical flaw?", "options": [{"label": "A", "text": "Oversampling", "is_correct": False}, {"label": "B", "text": "Ignoring meso-level dynamics that mediate macro and micro", "is_correct": True}, {"label": "C", "text": "Using incorrect statistics", "is_correct": False}, {"label": "D", "text": "Ethical violations", "is_correct": False}], "explanation": "Compliance is shaped by community norms; leaving out the meso layer breaks the causal chain."},
        {"difficulty": "hard", "question": "Climate analysis links individual energy use, city infrastructure, and global carbon markets. Critics say it is too complicated. What's the best rebuttal?", "options": [{"label": "A", "text": "Simplicity is always better", "is_correct": False}, {"label": "B", "text": "Climate outcomes depend on interactions across scales", "is_correct": True}, {"label": "C", "text": "It is easier to publish", "is_correct": False}, {"label": "D", "text": "Macro-only models are sufficient", "is_correct": False}], "explanation": "Cross-level feedbacks drive emissions and mitigation; ignoring them misleads policy."},
        {"difficulty": "hard", "question": "A sociologist studies individual bias, institutional discrimination, and legal frameworks to explain inequality. Which combination captures this approach?", "options": [{"label": "A", "text": "#levelsofanalysis and #complexcausality", "is_correct": True}, {"label": "B", "text": "#networks and #emergentproperties", "is_correct": False}, {"label": "C", "text": "#systemdynamics and #systemmapping", "is_correct": False}, {"label": "D", "text": "Simple causality and constraints", "is_correct": False}], "explanation": "The study connects multiple levels and shows how they interact to reinforce inequality."}
    ],
    "#networks": [
        {"difficulty": "easy", "question": "In complex systems, what is a network?", "options": [{"label": "A", "text": "Just a computer system", "is_correct": False}, {"label": "B", "text": "Nodes connected by edges representing relationships", "is_correct": True}, {"label": "C", "text": "A random group of unrelated individuals", "is_correct": False}, {"label": "D", "text": "A hierarchical chart only", "is_correct": False}], "explanation": "Networks model entities and their connections—people, cities, neurons, etc."},
        {"difficulty": "easy", "question": "Which metric measures how many direct connections a node has?", "options": [{"label": "A", "text": "Degree centrality", "is_correct": True}, {"label": "B", "text": "Clustering coefficient", "is_correct": False}, {"label": "C", "text": "Betweenness centrality", "is_correct": False}, {"label": "D", "text": "Average path length", "is_correct": False}], "explanation": "Degree counts immediate connections, reflecting direct reach inside a network."},
        {"difficulty": "medium", "question": "In a community with super-spreaders, disease spreads faster than in a uniform network. What network property explains this?", "options": [{"label": "A", "text": "Uniform degree distribution", "is_correct": False}, {"label": "B", "text": "Scale-free topology with high-degree hubs", "is_correct": True}, {"label": "C", "text": "Low clustering", "is_correct": False}, {"label": "D", "text": "Long average path length", "is_correct": False}], "explanation": "Hubs accelerate spread; scale-free networks have many low-degree nodes and a few hubs."},
        {"difficulty": "medium", "question": "One employee is the sole liaison between engineering and marketing. Removing them halts collaboration. Which centrality score is high?", "options": [{"label": "A", "text": "Degree centrality", "is_correct": False}, {"label": "B", "text": "Betweenness centrality", "is_correct": True}, {"label": "C", "text": "Closeness centrality", "is_correct": False}, {"label": "D", "text": "Eigenvector centrality", "is_correct": False}], "explanation": "Betweenness captures acting as a bridge between otherwise disconnected clusters."},
        {"difficulty": "medium", "question": "Social media networks show \"small-world\" properties: high clustering with short path lengths. Why does this enable rapid diffusion?", "options": [{"label": "A", "text": "Everyone knows everyone", "is_correct": False}, {"label": "B", "text": "Local clusters are bridged by long-range ties, shortening global paths", "is_correct": True}, {"label": "C", "text": "Information cannot spread", "is_correct": False}, {"label": "D", "text": "There are no hubs", "is_correct": False}], "explanation": "Short paths and clustering mean local outbreaks can jump quickly to distant clusters."},
        {"difficulty": "hard", "question": "A research collaboration network relies on a few highly connected scientists. Removing them fragments the network. Which concept applies?", "options": [{"label": "A", "text": "Scale-free topology with hub vulnerability", "is_correct": True}, {"label": "B", "text": "Random graph with uniform degree", "is_correct": False}, {"label": "C", "text": "Lattice network with regular structure", "is_correct": False}, {"label": "D", "text": "Complete graph with maximum density", "is_correct": False}], "explanation": "Scale-free networks function efficiently but rely heavily on hubs."},
        {"difficulty": "hard", "question": "A supply chain builds redundant routes between suppliers and manufacturers. A disaster hits one supplier but production continues via alternatives. What design principle explains resilience?", "options": [{"label": "A", "text": "Centralization", "is_correct": False}, {"label": "B", "text": "Redundancy and alternative pathways (network robustness)", "is_correct": True}, {"label": "C", "text": "Minimizing edges", "is_correct": False}, {"label": "D", "text": "Star topology", "is_correct": False}], "explanation": "Multiple pathways reduce vulnerability to single-point failures."},
        {"difficulty": "hard", "question": "To curb misinformation, analysts target high-betweenness accounts rather than high-degree celebrities. Why might this work better?", "options": [{"label": "A", "text": "Betweenness nodes are easier to locate", "is_correct": False}, {"label": "B", "text": "Betweenness nodes control pathways between clusters, so removing them fragments spread routes", "is_correct": True}, {"label": "C", "text": "Popular accounts do not matter", "is_correct": False}, {"label": "D", "text": "It costs less", "is_correct": False}], "explanation": "Bridge nodes keep clusters connected—removing them slows dissemination across communities."}
    ],
    "#systemdynamics": [
        {"difficulty": "easy", "question": "What is an attractor in system dynamics?", "options": [{"label": "A", "text": "A random fluctuation", "is_correct": False}, {"label": "B", "text": "A stable state the system tends to settle into", "is_correct": True}, {"label": "C", "text": "A temporary disruption", "is_correct": False}, {"label": "D", "text": "An initial condition", "is_correct": False}], "explanation": "Attractors represent enduring patterns or equilibria in a dynamic system."},
        {"difficulty": "easy", "question": "Which description matches a critical point or tipping point?", "options": [{"label": "A", "text": "A stable equilibrium", "is_correct": False}, {"label": "B", "text": "A threshold where small changes trigger a new system state", "is_correct": True}, {"label": "C", "text": "A random event", "is_correct": False}, {"label": "D", "text": "A measurement error", "is_correct": False}], "explanation": "Critical points separate basins of attraction—crossing them shifts the system."},
        {"difficulty": "medium", "question": "A lake remains clear for decades. Once fertilizer runoff passes a threshold, algae blooms persist even when runoff drops. Which concept explains this?", "options": [{"label": "A", "text": "Linear response", "is_correct": False}, {"label": "B", "text": "Hysteresis and alternative stable states", "is_correct": True}, {"label": "C", "text": "Random variation", "is_correct": False}, {"label": "D", "text": "Simple recovery", "is_correct": False}], "explanation": "The lake shifted from the clear-water attractor to the turbid-water attractor and cannot easily return."},
        {"difficulty": "medium", "question": "A company culture becomes competitive after aggressive metrics are introduced. Even after metrics are removed, competitive norms persist. Why?", "options": [{"label": "A", "text": "The system moved into a new attractor", "is_correct": True}, {"label": "B", "text": "It was random", "is_correct": False}, {"label": "C", "text": "Employees forgot old norms", "is_correct": False}, {"label": "D", "text": "Linear cause-effect explains it", "is_correct": False}], "explanation": "Over time a new stable state formed, and the organization settled into it."},
        {"difficulty": "medium", "question": "Wildfires spread slowly until wind speeds exceed 30 mph, then spread explosively. Which system dynamics feature appears?", "options": [{"label": "A", "text": "Linear scaling", "is_correct": False}, {"label": "B", "text": "Critical threshold leading to a regime shift", "is_correct": True}, {"label": "C", "text": "Steady-state equilibrium", "is_correct": False}, {"label": "D", "text": "Random walk", "is_correct": False}], "explanation": "Wind speed acts as a tipping point that changes fire behavior qualitatively."},
        {"difficulty": "hard", "question": "A financial market cycles between booms and busts. A credit crisis pushes it into deep recession, and recovery is slow. Analysts say it \"fell into a deep basin.\" What does that mean?", "options": [{"label": "A", "text": "The crisis was temporary", "is_correct": False}, {"label": "B", "text": "The system entered a strong recession attractor with a deep basin", "is_correct": True}, {"label": "C", "text": "Markets are random", "is_correct": False}, {"label": "D", "text": "No intervention can help", "is_correct": False}], "explanation": "Deep basins indicate stable states that require significant energy or policy to exit."},
        {"difficulty": "hard", "question": "Climate scientists warn that exceeding 2°C warming causes irreversible ice sheet collapse. Which system dynamics principle supports this?", "options": [{"label": "A", "text": "Linear temperature response", "is_correct": False}, {"label": "B", "text": "Crossing a critical threshold into a new attractor basin", "is_correct": True}, {"label": "C", "text": "Random fluctuations", "is_correct": False}, {"label": "D", "text": "Measurement uncertainty", "is_correct": False}], "explanation": "Beyond the threshold, positive feedbacks trigger a new stable state—ice-free conditions."},
        {"difficulty": "hard", "question": "Therapy nudges a patient from a depressive state to a healthy state. Progress is slow until a breakthrough, then stabilizes. Which concepts apply?", "options": [{"label": "A", "text": "Attractor escape, critical point crossing, and new attractor stabilization", "is_correct": True}, {"label": "B", "text": "Random recovery and linear improvement", "is_correct": False}, {"label": "C", "text": "Placebo effect only", "is_correct": False}, {"label": "D", "text": "Simple cause-effect", "is_correct": False}], "explanation": "Therapy helps the patient exit one basin, cross a threshold, and settle into a new stable state."}
    ],
    "#systemmapping": [
        {"difficulty": "easy", "question": "What is the primary purpose of system mapping?", "options": [{"label": "A", "text": "To create visually impressive diagrams", "is_correct": False}, {"label": "B", "text": "To represent components and relationships guided by an explanatory goal", "is_correct": True}, {"label": "C", "text": "To avoid detailed analysis", "is_correct": False}, {"label": "D", "text": "To list variables randomly", "is_correct": False}], "explanation": "System mapping organizes a system's structure so explanations can be tested and refined."},
        {"difficulty": "easy", "question": "Which tool is most associated with system mapping in complex systems?", "options": [{"label": "A", "text": "Gantt chart", "is_correct": False}, {"label": "B", "text": "ROC curve", "is_correct": False}, {"label": "C", "text": "Causal loop or stock-and-flow diagram", "is_correct": True}, {"label": "D", "text": "Confusion matrix", "is_correct": False}], "explanation": "Causal loop and stock-and-flow diagrams capture feedback structures in systems."},
        {"difficulty": "medium", "question": "A hospital maps patient flow by department to locate bottlenecks. Which decomposition principle is applied?", "options": [{"label": "A", "text": "Random grouping", "is_correct": False}, {"label": "B", "text": "Functional decomposition aligned with the explanatory goal", "is_correct": True}, {"label": "C", "text": "Historical sequencing", "is_correct": False}, {"label": "D", "text": "Alphabetical listing", "is_correct": False}], "explanation": "Grouping by function reveals structural bottlenecks relevant to the hospital's challenge."},
        {"difficulty": "medium", "question": "Researchers map a food system: farms → processors → distributors → retailers → consumers. Adding feedback loops (demand → production, waste → compost → farms) reveals what?", "options": [{"label": "A", "text": "The system is linear", "is_correct": False}, {"label": "B", "text": "Circular causality and resource flows", "is_correct": True}, {"label": "C", "text": "Farms are unimportant", "is_correct": False}, {"label": "D", "text": "Consumers play no role", "is_correct": False}], "explanation": "Feedback loops explain how outputs affect inputs—crucial for system understanding."},
        {"difficulty": "medium", "question": "One team maps transportation by mode (bus, car, bike) to reduce CO₂; another maps by socioeconomic group to address equity. What principle does this show?", "options": [{"label": "A", "text": "Different decompositions serve different explanatory challenges", "is_correct": True}, {"label": "B", "text": "Only one correct map exists", "is_correct": False}, {"label": "C", "text": "Mapping is arbitrary", "is_correct": False}, {"label": "D", "text": "Data collection alone matters", "is_correct": False}], "explanation": "System maps should align with the question—there is no universal \"best\" decomposition."},
        {"difficulty": "hard", "question": "A policy analyst maps homelessness drivers: individual (mental health), structural (housing costs), systemic (zoning). How does this map improve policy design?", "options": [{"label": "A", "text": "It simplifies to one factor", "is_correct": False}, {"label": "B", "text": "It reveals leverage points at multiple levels", "is_correct": True}, {"label": "C", "text": "It is too complex to use", "is_correct": False}, {"label": "D", "text": "It ignores individuals", "is_correct": False}], "explanation": "Mapping shows where interventions can disrupt feedback loops or address root causes."},
        {"difficulty": "hard", "question": "A corporation maps innovation and spots a bottleneck: projects generated but not funded. After adding a rapid funding loop, projects fail due to weak vetting. What mapping error occurred?", "options": [{"label": "A", "text": "Incomplete map—missing quality-control feedback", "is_correct": True}, {"label": "B", "text": "The map was too detailed", "is_correct": False}, {"label": "C", "text": "Mapping is useless", "is_correct": False}, {"label": "D", "text": "Implementation alone failed", "is_correct": False}], "explanation": "The system map omitted a crucial loop that feeds outcomes back into funding decisions."},
        {"difficulty": "hard", "question": "A climate researcher maps carbon flows and feedbacks to identify intervention points. Which HCs does this work exemplify?", "options": [{"label": "A", "text": "#systemmapping, #complexcausality, and #systemdynamics", "is_correct": True}, {"label": "B", "text": "#networks and #levelsofanalysis", "is_correct": False}, {"label": "C", "text": "Linear causality and constraints", "is_correct": False}, {"label": "D", "text": "#emergentproperties only", "is_correct": False}], "explanation": "Mapping decomposes flows, reveals interacting causes, and highlights feedback dynamics."}
    ]
}
