"""EA50 HC Question Bank
Structured MCQ items for every HC in the EA50 course.
Each question contains: difficulty, stem, options, correct answer flag, and explanation.
"""

EA50_HC_QUESTIONS = {
    "#rightproblem": [
        {"difficulty": "easy", "question": "What does 'solving the right problem' mean in EA50?", "options": [{"label": "A", "text": "Finding the fastest solution", "is_correct": False}, {"label": "B", "text": "Identifying the actual root problem before solving", "is_correct": True}, {"label": "C", "text": "Choosing the cheapest option", "is_correct": False}, {"label": "D", "text": "Delegating to experts", "is_correct": False}], "explanation": "EA50 emphasizes problem framing—ensuring you address the real issue, not symptoms."},
        {"difficulty": "easy", "question": "A company loses customers. Management blames sales staff and fires them, but churn continues. What went wrong?", "options": [{"label": "A", "text": "They solved the right problem", "is_correct": False}, {"label": "B", "text": "They addressed a symptom, not the root cause", "is_correct": True}, {"label": "C", "text": "Sales staff were irrelevant", "is_correct": False}, {"label": "D", "text": "No solution exists", "is_correct": False}], "explanation": "Firing staff treated a symptom; the real problem might be product quality or pricing."},
        {"difficulty": "medium", "question": "Traffic congestion downtown prompts a city to widen roads. Congestion returns within a year. Which principle was ignored?", "options": [{"label": "A", "text": "Linear scaling", "is_correct": False}, {"label": "B", "text": "Induced demand: widening roads invites more traffic", "is_correct": True}, {"label": "C", "text": "Random variation", "is_correct": False}, {"label": "D", "text": "Budget constraints", "is_correct": False}], "explanation": "The 'right problem' was to reduce car dependency, not add capacity that induces more driving."},
        {"difficulty": "medium", "question": "Students struggle with a tough exam. A professor curves grades but complaints persist. What's the underlying problem?", "options": [{"label": "A", "text": "Grade distribution", "is_correct": False}, {"label": "B", "text": "Exam difficulty or unclear teaching, not grade scale", "is_correct": True}, {"label": "C", "text": "Student effort", "is_correct": False}, {"label": "D", "text": "Random chance", "is_correct": False}], "explanation": "Curving addresses symptoms; the root issue is exam alignment with learning objectives."},
        {"difficulty": "medium", "question": "A hospital treats recurring infections by prescribing more antibiotics, but resistance rises. Which HC was neglected?", "options": [{"label": "A", "text": "#rightproblem", "is_correct": True}, {"label": "B", "text": "#constraints", "is_correct": False}, {"label": "C", "text": "#heuristics", "is_correct": False}, {"label": "D", "text": "#breakitdown", "is_correct": False}], "explanation": "The real problem is infection prevention, not treatment escalation."},
        {"difficulty": "hard", "question": "A tech startup loses users. They redesign the UI but churn continues. Research reveals users leave because a competitor offers better customer support. What does this illustrate?", "options": [{"label": "A", "text": "UI was irrelevant to the real problem", "is_correct": True}, {"label": "B", "text": "Users are irrational", "is_correct": False}, {"label": "C", "text": "Competitors always win", "is_correct": False}, {"label": "D", "text": "The solution was correct", "is_correct": False}], "explanation": "They solved the wrong problem—UX wasn't the issue; support quality was."},
        {"difficulty": "hard", "question": "A country enacts strict penalties for drug possession to reduce addiction. Addiction rates stay flat but incarceration spikes. What principle applies?", "options": [{"label": "A", "text": "The intervention addressed symptoms (possession), not the root (addiction drivers)", "is_correct": True}, {"label": "B", "text": "Penalties were too lenient", "is_correct": False}, {"label": "C", "text": "Random policy effects", "is_correct": False}, {"label": "D", "text": "Addiction is unsolvable", "is_correct": False}], "explanation": "The 'right problem' is addiction causes (trauma, access to treatment), not criminalization."},
        {"difficulty": "hard", "question": "An e-commerce site optimizes checkout speed but cart abandonment remains high. User testing reveals trust issues with payment security. Which EA50 concept guides the fix?", "options": [{"label": "A", "text": "#rightproblem—reframe from speed to trust", "is_correct": True}, {"label": "B", "text": "#heuristics—apply a shortcut", "is_correct": False}, {"label": "C", "text": "#constraints—accept limits", "is_correct": False}, {"label": "D", "text": "#breakitdown—decompose checkout", "is_correct": False}], "explanation": "The real barrier was trust, not speed; identifying the right problem drives effective solutions."}
    ],
    "#analogies": [
        {"difficulty": "easy", "question": "What is analogical reasoning?", "options": [{"label": "A", "text": "Memorizing formulas", "is_correct": False}, {"label": "B", "text": "Transferring knowledge from a familiar domain to solve a new problem", "is_correct": True}, {"label": "C", "text": "Random guessing", "is_correct": False}, {"label": "D", "text": "Avoiding comparisons", "is_correct": False}], "explanation": "Analogies map structures between known and novel situations to guide problem-solving."},
        {"difficulty": "easy", "question": "Which example demonstrates analogical reasoning?", "options": [{"label": "A", "text": "Reciting a textbook definition", "is_correct": False}, {"label": "B", "text": "Comparing the heart to a pump to understand circulation", "is_correct": True}, {"label": "C", "text": "Solving 2 + 2", "is_correct": False}, {"label": "D", "text": "Following a recipe exactly", "is_correct": False}], "explanation": "The pump analogy maps mechanical principles onto the biological heart."},
        {"difficulty": "medium", "question": "A designer struggling with information architecture studies city maps and applies zoning principles. Which reasoning process is this?", "options": [{"label": "A", "text": "Deduction", "is_correct": False}, {"label": "B", "text": "Analogical transfer from urban planning to UI design", "is_correct": True}, {"label": "C", "text": "Induction", "is_correct": False}, {"label": "D", "text": "Random trial and error", "is_correct": False}], "explanation": "The designer uses city planning structures as an analogy for organizing digital content."},
        {"difficulty": "medium", "question": "Analogies can fail when surface similarities mask structural differences. Which scenario shows this risk?", "options": [{"label": "A", "text": "Comparing the brain to a computer, ignoring neuroplasticity", "is_correct": True}, {"label": "B", "text": "Using a map to navigate", "is_correct": False}, {"label": "C", "text": "Applying physics to engineering", "is_correct": False}, {"label": "D", "text": "Copying a proven recipe", "is_correct": False}], "explanation": "Brains and computers differ in adaptability; superficial analogy misleads if structural mismatch is ignored."},
        {"difficulty": "medium", "question": "A business leader reads about Toyota's lean manufacturing and applies it to software development (Agile). What EA50 HC is exemplified?", "options": [{"label": "A", "text": "#analogies", "is_correct": True}, {"label": "B", "text": "#constraints", "is_correct": False}, {"label": "C", "text": "#heuristics", "is_correct": False}, {"label": "D", "text": "#gapanalysis", "is_correct": False}], "explanation": "Transferring lean principles across domains demonstrates analogical reasoning."},
        {"difficulty": "hard", "question": "A policy analyst compares welfare reform to corporate restructuring, but critics argue citizens aren't employees. What's the critique?", "options": [{"label": "A", "text": "The analogy ignores key structural differences (rights, power dynamics)", "is_correct": True}, {"label": "B", "text": "Analogies never work", "is_correct": False}, {"label": "C", "text": "The analogy is too simple", "is_correct": False}, {"label": "D", "text": "Policies cannot use analogies", "is_correct": False}], "explanation": "Valid analogies require structural alignment; this one breaks down under scrutiny."},
        {"difficulty": "hard", "question": "A scientist models disease spread using network theory from computer science. This works until hospitals become overwhelmed, violating network assumptions. What lesson emerges?", "options": [{"label": "A", "text": "Analogies must be validated and refined when constraints appear", "is_correct": True}, {"label": "B", "text": "Network theory is useless", "is_correct": False}, {"label": "C", "text": "Analogies are always perfect", "is_correct": False}, {"label": "D", "text": "Models don't matter", "is_correct": False}], "explanation": "Effective analogical reasoning requires checking boundary conditions and adapting the mapping."},
        {"difficulty": "hard", "question": "A legal scholar uses First Amendment precedent to argue for online speech rights. Opponents say platforms aren't public squares. Which EA50 concept frames this debate?", "options": [{"label": "A", "text": "#analogies—does the public-square analogy hold structurally?", "is_correct": True}, {"label": "B", "text": "#constraints—legal limits matter most", "is_correct": False}, {"label": "C", "text": "#breakitdown—decompose arguments", "is_correct": False}, {"label": "D", "text": "#heuristics—apply a rule of thumb", "is_correct": False}], "explanation": "The debate centers on whether the analogy's structure (public access, regulation) applies to private platforms."}
    ],
    "#constraints": [
        {"difficulty": "easy", "question": "What are constraints in problem-solving?", "options": [{"label": "A", "text": "Unnecessary obstacles", "is_correct": False}, {"label": "B", "text": "Boundaries that shape and limit solutions", "is_correct": True}, {"label": "C", "text": "Random difficulties", "is_correct": False}, {"label": "D", "text": "Excuses for failure", "is_correct": False}], "explanation": "Constraints define the solution space—budget, time, laws, resources, physics."},
        {"difficulty": "easy", "question": "Which is an example of a hard constraint?", "options": [{"label": "A", "text": "A preference for blue over red", "is_correct": False}, {"label": "B", "text": "A legal requirement that cannot be violated", "is_correct": True}, {"label": "C", "text": "A suggestion to finish early", "is_correct": False}, {"label": "D", "text": "A marketing slogan", "is_correct": False}], "explanation": "Hard constraints are non-negotiable (laws, physical limits); soft constraints are preferences."},
        {"difficulty": "medium", "question": "A project team wants a feature-rich app but has a two-week deadline. Which EA50 principle applies?", "options": [{"label": "A", "text": "Ignore constraints", "is_correct": False}, {"label": "B", "text": "Recognize time as a constraint and prioritize features", "is_correct": True}, {"label": "C", "text": "Add unlimited resources", "is_correct": False}, {"label": "D", "text": "Abandon the project", "is_correct": False}], "explanation": "Effective problem-solving acknowledges constraints and adapts scope accordingly."},
        {"difficulty": "medium", "question": "A nonprofit wants to serve all communities but has limited funding. How should they proceed under #constraints?", "options": [{"label": "A", "text": "Spread funding thinly everywhere", "is_correct": False}, {"label": "B", "text": "Prioritize high-impact areas given budget limits", "is_correct": True}, {"label": "C", "text": "Refuse to acknowledge limits", "is_correct": False}, {"label": "D", "text": "Abandon the mission", "is_correct": False}], "explanation": "Constraints force strategic prioritization—a core EA50 lesson."},
        {"difficulty": "medium", "question": "An engineer designs a bridge but is constrained by soil quality and budget. Which approach is best?", "options": [{"label": "A", "text": "Ignore soil data", "is_correct": False}, {"label": "B", "text": "Design within physical and financial constraints", "is_correct": True}, {"label": "C", "text": "Demand unlimited funds", "is_correct": False}, {"label": "D", "text": "Build anyway and hope", "is_correct": False}], "explanation": "Sound engineering respects constraints; ignoring them causes failure."},
        {"difficulty": "hard", "question": "A startup pivots from B2C to B2B after realizing consumer acquisition costs exceed runway. What principle guided this?", "options": [{"label": "A", "text": "Recognizing financial constraints and adapting strategy", "is_correct": True}, {"label": "B", "text": "Random experimentation", "is_correct": False}, {"label": "C", "text": "Ignoring market signals", "is_correct": False}, {"label": "D", "text": "Blind persistence", "is_correct": False}], "explanation": "The pivot acknowledged the cash constraint and sought a viable path within it."},
        {"difficulty": "hard", "question": "A government plans universal healthcare but faces budget and political opposition. Analysts propose incremental expansion. Which EA50 HC explains this?", "options": [{"label": "A", "text": "#constraints—work within fiscal and political limits", "is_correct": True}, {"label": "B", "text": "#analogies—compare to other countries", "is_correct": False}, {"label": "C", "text": "#heuristics—use a shortcut", "is_correct": False}, {"label": "D", "text": "#gapanalysis—measure coverage gap", "is_correct": False}], "explanation": "Recognizing hard constraints leads to feasible, staged solutions rather than unachievable ideals."},
        {"difficulty": "hard", "question": "A climate scientist says we must reduce emissions 50% in 10 years, but economic models show 30% is feasible. Policymakers target 30%. Critics call this defeatist. What's the EA50 perspective?", "options": [{"label": "A", "text": "Acknowledge economic and political constraints while seeking to relax them over time", "is_correct": True}, {"label": "B", "text": "Ignore feasibility and demand 50%", "is_correct": False}, {"label": "C", "text": "Give up on climate action", "is_correct": False}, {"label": "D", "text": "Constraints are irrelevant", "is_correct": False}], "explanation": "EA50 teaches balancing ambition with real-world constraints, then working to shift those constraints."}
    ],
    "#heuristics": [
        {"difficulty": "easy", "question": "What is a heuristic?", "options": [{"label": "A", "text": "A guaranteed optimal solution", "is_correct": False}, {"label": "B", "text": "A mental shortcut or rule of thumb for decision-making", "is_correct": True}, {"label": "C", "text": "A random guess", "is_correct": False}, {"label": "D", "text": "A formal proof", "is_correct": False}], "explanation": "Heuristics are fast, approximate strategies that work well in many situations but aren't perfect."},
        {"difficulty": "easy", "question": "Which is an example of a heuristic?", "options": [{"label": "A", "text": "Calculating optimal portfolio allocation with linear programming", "is_correct": False}, {"label": "B", "text": "Using 'buy low, sell high' as an investment guide", "is_correct": True}, {"label": "C", "text": "Solving a system of equations", "is_correct": False}, {"label": "D", "text": "Memorizing formulas", "is_correct": False}], "explanation": "'Buy low, sell high' is a heuristic—simple, actionable, but not a precise algorithm."},
        {"difficulty": "medium", "question": "A doctor uses the heuristic 'common things occur commonly' to diagnose a cough as a cold, not a rare disease. When is this heuristic problematic?", "options": [{"label": "A", "text": "Always—it's useless", "is_correct": False}, {"label": "B", "text": "When rare but serious conditions are missed", "is_correct": True}, {"label": "C", "text": "Never—it's always correct", "is_correct": False}, {"label": "D", "text": "Only in textbooks", "is_correct": False}], "explanation": "Heuristics fail at boundary cases; over-reliance can miss critical outliers."},
        {"difficulty": "medium", "question": "A manager uses '80/20 rule' (80% of results from 20% of efforts) to prioritize tasks. Which EA50 HC is this?", "options": [{"label": "A", "text": "#heuristics", "is_correct": True}, {"label": "B", "text": "#constraints", "is_correct": False}, {"label": "C", "text": "#analogies", "is_correct": False}, {"label": "D", "text": "#breakitdown", "is_correct": False}], "explanation": "The 80/20 rule is a heuristic for resource allocation."},
        {"difficulty": "medium", "question": "Students learn 'if it sounds too good to be true, it probably is' to evaluate claims. What's the benefit and risk?", "options": [{"label": "A", "text": "Benefit: quick skepticism filter; Risk: dismissing legitimate innovations", "is_correct": True}, {"label": "B", "text": "No benefit or risk", "is_correct": False}, {"label": "C", "text": "Benefit: always correct; Risk: none", "is_correct": False}, {"label": "D", "text": "Pure bias", "is_correct": False}], "explanation": "Heuristics offer efficiency but can produce false negatives when misapplied."},
        {"difficulty": "hard", "question": "An investor follows 'diversify your portfolio' as a heuristic. In a systemic market crash, all assets fall. What does this reveal?", "options": [{"label": "A", "text": "Heuristics fail when underlying assumptions (asset independence) break", "is_correct": True}, {"label": "B", "text": "Diversification is pointless", "is_correct": False}, {"label": "C", "text": "Heuristics always work", "is_correct": False}, {"label": "D", "text": "Investors are irrational", "is_correct": False}], "explanation": "Diversification works under normal conditions but falters in correlated crashes—heuristics have limits."},
        {"difficulty": "hard", "question": "A hiring manager uses 'hire from top schools' as a heuristic. Research shows this introduces bias and excludes talent. How should EA50 frame this?", "options": [{"label": "A", "text": "Heuristics must be validated and refined when they produce systematic errors", "is_correct": True}, {"label": "B", "text": "Heuristics are evil", "is_correct": False}, {"label": "C", "text": "Always use heuristics uncritically", "is_correct": False}, {"label": "D", "text": "Eliminate all decision shortcuts", "is_correct": False}], "explanation": "EA50 teaches reflective use—recognize when heuristics degrade outcomes and adapt."},
        {"difficulty": "hard", "question": "A software team uses 'fail fast' (quickly test and discard bad ideas). In a high-stakes medical device project, this causes safety issues. What's the lesson?", "options": [{"label": "A", "text": "Context matters—heuristics effective in one domain may be harmful in another", "is_correct": True}, {"label": "B", "text": "'Fail fast' is universally wrong", "is_correct": False}, {"label": "C", "text": "Heuristics don't need context", "is_correct": False}, {"label": "D", "text": "Discard all heuristics", "is_correct": False}], "explanation": "EA50 emphasizes domain-appropriate heuristics; what works for startups may fail in safety-critical fields."}
    ],
    "#scienceoflearning": [
        {"difficulty": "easy", "question": "What does the science of learning study?", "options": [{"label": "A", "text": "Random educational trends", "is_correct": False}, {"label": "B", "text": "Evidence-based principles of how people learn effectively", "is_correct": True}, {"label": "C", "text": "Historical teaching methods", "is_correct": False}, {"label": "D", "text": "Personal opinions about education", "is_correct": False}], "explanation": "Science of learning applies cognitive science to understand and improve learning outcomes."},
        {"difficulty": "easy", "question": "Which technique is supported by the science of learning?", "options": [{"label": "A", "text": "Cramming the night before an exam", "is_correct": False}, {"label": "B", "text": "Spaced repetition over time", "is_correct": True}, {"label": "C", "text": "Passive rereading only", "is_correct": False}, {"label": "D", "text": "Avoiding practice tests", "is_correct": False}], "explanation": "Spaced repetition enhances long-term retention—a core finding in learning science."},
        {"difficulty": "medium", "question": "A student highlights every sentence in a textbook but performs poorly on exams. What does learning science suggest?", "options": [{"label": "A", "text": "Highlighting is the best strategy", "is_correct": False}, {"label": "B", "text": "Passive highlighting creates illusion of learning without deep processing", "is_correct": True}, {"label": "C", "text": "The student is incapable", "is_correct": False}, {"label": "D", "text": "Exams are unfair", "is_correct": False}], "explanation": "Active retrieval and elaboration matter more than surface-level highlighting."},
        {"difficulty": "medium", "question": "A teacher uses retrieval practice (frequent low-stakes quizzes). Students initially complain but long-term retention improves. Why?", "options": [{"label": "A", "text": "Testing is punitive", "is_correct": False}, {"label": "B", "text": "Retrieval strengthens memory consolidation", "is_correct": True}, {"label": "C", "text": "It's easier for the teacher", "is_correct": False}, {"label": "D", "text": "Random luck", "is_correct": False}], "explanation": "Retrieval practice is a high-impact strategy supported by learning science."},
        {"difficulty": "medium", "question": "Interleaving (mixing problem types) initially slows learning but improves transfer. Which EA50 HC does this exemplify?", "options": [{"label": "A", "text": "#scienceoflearning", "is_correct": True}, {"label": "B", "text": "#heuristics", "is_correct": False}, {"label": "C", "text": "#constraints", "is_correct": False}, {"label": "D", "text": "#breakitdown", "is_correct": False}], "explanation": "Interleaving is an evidence-based learning technique."},
        {"difficulty": "hard", "question": "A professor lectures for 90 minutes. Cognitive load research suggests students retain little after 15-20 minutes. What's the implication?", "options": [{"label": "A", "text": "Students are lazy", "is_correct": False}, {"label": "B", "text": "Chunk lectures with active learning breaks to manage cognitive load", "is_correct": True}, {"label": "C", "text": "Lectures are always effective", "is_correct": False}, {"label": "D", "text": "Ignore cognitive limits", "is_correct": False}], "explanation": "Learning science shows attention and working memory have limits; instructional design should adapt."},
        {"difficulty": "hard", "question": "An online course uses videos, readings, and practice. Completion rates are low. Learning science suggests adding social accountability and deadlines. Why?", "options": [{"label": "A", "text": "Motivation and structure support self-regulated learning", "is_correct": True}, {"label": "B", "text": "Content is bad", "is_correct": False}, {"label": "C", "text": "Students are unmotivated", "is_correct": False}, {"label": "D", "text": "Random variation", "is_correct": False}], "explanation": "Metacognitive scaffolding (deadlines, peer interaction) enhances persistence—a learning science insight."},
        {"difficulty": "hard", "question": "A tutoring program uses elaborative interrogation ('why' questions) and self-explanation. Students outperform those using passive review. Which principle explains this?", "options": [{"label": "A", "text": "Generative learning strategies deepen understanding", "is_correct": True}, {"label": "B", "text": "Time spent matters most", "is_correct": False}, {"label": "C", "text": "Intelligence is fixed", "is_correct": False}, {"label": "D", "text": "Rereading is optimal", "is_correct": False}], "explanation": "Elaboration and self-explanation force active processing, a robust finding in learning science."}
    ],
    "#breakitdown": [
        {"difficulty": "easy", "question": "What does 'break it down' mean in problem-solving?", "options": [{"label": "A", "text": "Give up on the problem", "is_correct": False}, {"label": "B", "text": "Decompose a complex problem into smaller, manageable parts", "is_correct": True}, {"label": "C", "text": "Ignore complexity", "is_correct": False}, {"label": "D", "text": "Solve everything at once", "is_correct": False}], "explanation": "Breaking down reduces cognitive load and enables systematic progress."},
        {"difficulty": "easy", "question": "Which approach demonstrates 'breaking it down'?", "options": [{"label": "A", "text": "Tackling a 20-page essay by writing one section at a time", "is_correct": True}, {"label": "B", "text": "Staring at the blank page", "is_correct": False}, {"label": "C", "text": "Writing randomly without structure", "is_correct": False}, {"label": "D", "text": "Waiting for inspiration", "is_correct": False}], "explanation": "Sectioning the essay is decomposition—a core EA50 strategy."},
        {"difficulty": "medium", "question": "A software project is overwhelming. The team creates user stories, sprints, and milestones. Which HC is applied?", "options": [{"label": "A", "text": "#breakitdown", "is_correct": True}, {"label": "B", "text": "#heuristics", "is_correct": False}, {"label": "C", "text": "#constraints", "is_correct": False}, {"label": "D", "text": "#analogies", "is_correct": False}], "explanation": "Decomposing the project into stories and sprints is 'breaking it down'."},
        {"difficulty": "medium", "question": "A student faces a challenging math proof. Breaking it down means:", "options": [{"label": "A", "text": "Giving up", "is_correct": False}, {"label": "B", "text": "Identifying sub-goals and proving each step", "is_correct": True}, {"label": "C", "text": "Memorizing the answer", "is_correct": False}, {"label": "D", "text": "Skipping the proof", "is_correct": False}], "explanation": "Decomposing into lemmas and sub-proofs makes complex reasoning tractable."},
        {"difficulty": "medium", "question": "A nonprofit wants to reduce homelessness. Breaking it down involves:", "options": [{"label": "A", "text": "Addressing all causes simultaneously without prioritization", "is_correct": False}, {"label": "B", "text": "Identifying sub-problems: housing, mental health, employment, then tackling each", "is_correct": True}, {"label": "C", "text": "Ignoring root causes", "is_correct": False}, {"label": "D", "text": "Waiting for a silver bullet", "is_correct": False}], "explanation": "Decomposition enables focused interventions on tractable components."},
        {"difficulty": "hard", "question": "A startup aims to 'disrupt healthcare'. Early efforts fail because the problem is too broad. What should they do?", "options": [{"label": "A", "text": "Persist without change", "is_correct": False}, {"label": "B", "text": "Break it down: focus on one sub-problem (e.g., appointment scheduling) and solve it well", "is_correct": True}, {"label": "C", "text": "Abandon the mission", "is_correct": False}, {"label": "D", "text": "Blame the market", "is_correct": False}], "explanation": "Successful innovation often starts by breaking down grand visions into solvable chunks."},
        {"difficulty": "hard", "question": "A researcher studies inequality. They decompose it into income, wealth, education, and health disparities. Critics say this ignores intersections. What's the EA50 take?", "options": [{"label": "A", "text": "Decomposition is a starting point; interactions must be re-integrated", "is_correct": True}, {"label": "B", "text": "Never break problems down", "is_correct": False}, {"label": "C", "text": "Decomposition is always sufficient", "is_correct": False}, {"label": "D", "text": "Ignore interactions", "is_correct": False}], "explanation": "EA50 teaches breaking down as a tool, but recognizes complex problems require synthesis after decomposition."},
        {"difficulty": "hard", "question": "A policy team decomposes climate action into energy, transport, agriculture, and industry. Each sector optimizes independently but overall emissions rise due to rebound effects. What's missing?", "options": [{"label": "A", "text": "Cross-sector integration and feedback analysis", "is_correct": True}, {"label": "B", "text": "More decomposition", "is_correct": False}, {"label": "C", "text": "Abandoning decomposition", "is_correct": False}, {"label": "D", "text": "Random policy changes", "is_correct": False}], "explanation": "Breaking it down is necessary but insufficient; systems thinking must follow to capture interactions."}
    ],
    "#gapanalysis": [
        {"difficulty": "easy", "question": "What is gap analysis?", "options": [{"label": "A", "text": "Ignoring current state", "is_correct": False}, {"label": "B", "text": "Identifying the difference between current state and desired goal", "is_correct": True}, {"label": "C", "text": "Setting vague goals", "is_correct": False}, {"label": "D", "text": "Accepting status quo", "is_correct": False}], "explanation": "Gap analysis clarifies what must change to reach a goal."},
        {"difficulty": "easy", "question": "A student scores 60% and wants 90%. Gap analysis involves:", "options": [{"label": "A", "text": "Ignoring the 60%", "is_correct": False}, {"label": "B", "text": "Identifying the 30-point gap and actions needed to close it", "is_correct": True}, {"label": "C", "text": "Lowering the goal to 60%", "is_correct": False}, {"label": "D", "text": "Blaming the test", "is_correct": False}], "explanation": "Gap analysis defines the current-to-target delta and informs strategy."},
        {"difficulty": "medium", "question": "A company has 10% market share and wants 25%. Gap analysis would reveal:", "options": [{"label": "A", "text": "The 15-point gap and drivers: brand, distribution, pricing, etc.", "is_correct": True}, {"label": "B", "text": "Nothing useful", "is_correct": False}, {"label": "C", "text": "That goals are irrelevant", "is_correct": False}, {"label": "D", "text": "Random factors", "is_correct": False}], "explanation": "Quantifying the gap and understanding barriers guides actionable plans."},
        {"difficulty": "medium", "question": "A city wants zero traffic deaths (Vision Zero) but currently has 100/year. Gap analysis means:", "options": [{"label": "A", "text": "Ignoring the 100 deaths", "is_correct": False}, {"label": "B", "text": "Identifying causes of 100 deaths and interventions to eliminate them", "is_correct": True}, {"label": "C", "text": "Accepting 100 as inevitable", "is_correct": False}, {"label": "D", "text": "Setting no goal", "is_correct": False}], "explanation": "Gap analysis bridges aspiration and reality through targeted action."},
        {"difficulty": "medium", "question": "A nonprofit aims to serve 5,000 clients but reaches 1,000. Gap analysis should examine:", "options": [{"label": "A", "text": "The 4,000-client gap and capacity, outreach, or funding barriers", "is_correct": True}, {"label": "B", "text": "Only celebrate the 1,000", "is_correct": False}, {"label": "C", "text": "Lower the goal to 1,000", "is_correct": False}, {"label": "D", "text": "Blame clients", "is_correct": False}], "explanation": "Gap analysis is diagnostic—revealing why goals aren't met and what to adjust."},
        {"difficulty": "hard", "question": "A country targets 50% renewable energy by 2030 but is at 15% in 2025. Gap analysis reveals slow infrastructure build and regulatory delays. What's the EA50 recommendation?", "options": [{"label": "A", "text": "Prioritize closing infrastructure and policy gaps with concrete timelines", "is_correct": True}, {"label": "B", "text": "Ignore the gap", "is_correct": False}, {"label": "C", "text": "Abandon the goal", "is_correct": False}, {"label": "D", "text": "Hope for change", "is_correct": False}], "explanation": "Gap analysis translates aspiration into action by identifying bottlenecks."},
        {"difficulty": "hard", "question": "A startup's revenue is $100K; they need $1M to break even. Gap analysis shows customer acquisition cost is too high. What's next?", "options": [{"label": "A", "text": "Reduce CAC or increase customer lifetime value to close the gap", "is_correct": True}, {"label": "B", "text": "Ignore unit economics", "is_correct": False}, {"label": "C", "text": "Raise more funding indefinitely", "is_correct": False}, {"label": "D", "text": "Accept losses forever", "is_correct": False}], "explanation": "Gap analysis identifies root causes; addressing them enables progress toward viability."},
        {"difficulty": "hard", "question": "A university wants 40% STEM graduates but produces 20%. Gap analysis reveals pipeline leaks: attrition in intro courses and lack of support. Which EA50 HC applies?", "options": [{"label": "A", "text": "#gapanalysis—diagnose where students exit and intervene", "is_correct": True}, {"label": "B", "text": "#heuristics—use a rule of thumb", "is_correct": False}, {"label": "C", "text": "#analogies—compare to other schools", "is_correct": False}, {"label": "D", "text": "#constraints—accept limits", "is_correct": False}], "explanation": "Gap analysis pinpoints leakage points; interventions then target those stages."}
    ]
}
