"""FA50 HC Question Bank
Structured MCQ items for every HC in the FA50 course.
Each question contains: difficulty, stem, options, correct answer flag, and explanation.
"""

FA50_HC_QUESTIONS = {
    "#algorithms": [
        {"difficulty": "easy", "question": "What is an algorithm?", "options": [{"label": "A", "text": "A random process", "is_correct": False}, {"label": "B", "text": "A step-by-step procedure to solve a problem", "is_correct": True}, {"label": "C", "text": "A guess", "is_correct": False}, {"label": "D", "text": "An opinion", "is_correct": False}], "explanation": "Algorithms are systematic, repeatable procedures."},
        {"difficulty": "easy", "question": "Which is an example of an algorithm?", "options": [{"label": "A", "text": "Flipping a coin", "is_correct": False}, {"label": "B", "text": "A recipe for baking a cake", "is_correct": True}, {"label": "C", "text": "Random guessing", "is_correct": False}, {"label": "D", "text": "Free association", "is_correct": False}], "explanation": "A recipe is a procedural algorithm with ordered steps."},
        {"difficulty": "medium", "question": "A delivery company routes trucks by always choosing the nearest unvisited customer. This is a 'greedy' algorithm. What's the risk?", "options": [{"label": "A", "text": "It guarantees the optimal global solution", "is_correct": False}, {"label": "B", "text": "It may produce locally optimal but globally suboptimal routes", "is_correct": True}, {"label": "C", "text": "It is always random", "is_correct": False}, {"label": "D", "text": "It never works", "is_correct": False}], "explanation": "Greedy algorithms are fast but can miss better overall solutions."},
        {"difficulty": "medium", "question": "Binary search repeatedly halves the search space. Why is this algorithmic thinking important?", "options": [{"label": "A", "text": "It is slower than linear search", "is_correct": False}, {"label": "B", "text": "It reduces problem size exponentially, demonstrating efficiency gains", "is_correct": True}, {"label": "C", "text": "It applies only to computers", "is_correct": False}, {"label": "D", "text": "It is random", "is_correct": False}], "explanation": "Algorithmic efficiency (O(log n)) vs brute force (O(n)) shows the power of systematic procedures."},
        {"difficulty": "medium", "question": "A student solves a math problem by memorizing steps without understanding. Which FA50 concept is missing?", "options": [{"label": "A", "text": "#algorithms—understanding the logic behind the procedure", "is_correct": True}, {"label": "B", "text": "#fallacies—avoiding errors", "is_correct": False}, {"label": "C", "text": "#estimation—approximating", "is_correct": False}, {"label": "D", "text": "#induction—generalizing", "is_correct": False}], "explanation": "True algorithmic thinking involves understanding why steps work, not just rote execution."},
        {"difficulty": "hard", "question": "An AI sorts resumes using a learned algorithm. It systematically rejects qualified women due to biased training data. What does this reveal?", "options": [{"label": "A", "text": "Algorithms are neutral and objective", "is_correct": False}, {"label": "B", "text": "Algorithms encode the biases present in their design and data", "is_correct": True}, {"label": "C", "text": "Automation eliminates bias", "is_correct": False}, {"label": "D", "text": "Algorithms are always fair", "is_correct": False}], "explanation": "FA50 teaches critical examination of algorithmic assumptions and inputs."},
        {"difficulty": "hard", "question": "A hospital uses a triage algorithm prioritizing patients by severity. During a surge, it fails because it doesn't account for resource constraints. What's the lesson?", "options": [{"label": "A", "text": "Algorithms must be validated under edge cases and updated when conditions change", "is_correct": True}, {"label": "B", "text": "Algorithms never fail", "is_correct": False}, {"label": "C", "text": "Triage is unnecessary", "is_correct": False}, {"label": "D", "text": "Abandon systematic procedures", "is_correct": False}], "explanation": "Effective algorithms require testing boundary conditions and adapting to context."},
        {"difficulty": "hard", "question": "A finance algorithm executes thousands of trades per second. A bug causes a flash crash. Which FA50 principle applies?", "options": [{"label": "A", "text": "Speed matters more than correctness", "is_correct": False}, {"label": "B", "text": "Algorithmic systems require rigorous validation and fail-safes", "is_correct": True}, {"label": "C", "text": "Algorithms are infallible", "is_correct": False}, {"label": "D", "text": "Human oversight is obsolete", "is_correct": False}], "explanation": "FA50 emphasizes understanding failure modes and building robust algorithmic systems."}
    ],
    "#estimation": [
        {"difficulty": "easy", "question": "What is estimation in formal thinking?", "options": [{"label": "A", "text": "Wild guessing", "is_correct": False}, {"label": "B", "text": "Making reasoned approximations when exact data is unavailable", "is_correct": True}, {"label": "C", "text": "Ignoring numbers", "is_correct": False}, {"label": "D", "text": "Always being precise", "is_correct": False}], "explanation": "Estimation uses logic and rough data to get ballpark answers quickly."},
        {"difficulty": "easy", "question": "Which is an example of estimation?", "options": [{"label": "A", "text": "Counting every grain of sand on a beach", "is_correct": False}, {"label": "B", "text": "Estimating beach sand grains using volume and grain size", "is_correct": True}, {"label": "C", "text": "Refusing to answer without exact data", "is_correct": False}, {"label": "D", "text": "Making up random numbers", "is_correct": False}], "explanation": "Fermi estimation breaks down problems and uses order-of-magnitude reasoning."},
        {"difficulty": "medium", "question": "Estimate the number of piano tuners in a city of 1 million. Which approach demonstrates FA50 estimation?", "options": [{"label": "A", "text": "Give up because you don't know exactly", "is_correct": False}, {"label": "B", "text": "Estimate households, piano ownership rate, tuning frequency, and tuners' capacity", "is_correct": True}, {"label": "C", "text": "Guess randomly", "is_correct": False}, {"label": "D", "text": "Refuse to estimate", "is_correct": False}], "explanation": "Fermi problems build estimates from assumptions and logic."},
        {"difficulty": "medium", "question": "A business forecasts revenue. They estimate conservatively (low) and optimistically (high), then take the midpoint. Why is this useful?", "options": [{"label": "A", "text": "It eliminates uncertainty", "is_correct": False}, {"label": "B", "text": "It bounds the estimate and acknowledges uncertainty", "is_correct": True}, {"label": "C", "text": "It is always accurate", "is_correct": False}, {"label": "D", "text": "It avoids thinking", "is_correct": False}], "explanation": "Range estimation is a robust FA50 technique for decision-making under uncertainty."},
        {"difficulty": "medium", "question": "Engineers estimate bridge load capacity before detailed simulations. Why start with estimation?", "options": [{"label": "A", "text": "Estimation is faster and reveals whether detailed analysis is warranted", "is_correct": True}, {"label": "B", "text": "Estimation replaces all analysis", "is_correct": False}, {"label": "C", "text": "Engineers avoid math", "is_correct": False}, {"label": "D", "text": "It is random", "is_correct": False}], "explanation": "Quick estimates guide resource allocation and feasibility checks."},
        {"difficulty": "hard", "question": "A policy analyst estimates climate mitigation costs. Critics demand exact figures. What's the FA50 defense of estimation?", "options": [{"label": "A", "text": "Estimation is lazy", "is_correct": False}, {"label": "B", "text": "In complex systems, rough estimates guide decisions when precision is impossible or costly", "is_correct": True}, {"label": "C", "text": "Exact figures are always available", "is_correct": False}, {"label": "D", "text": "Ignore uncertainty", "is_correct": False}], "explanation": "FA50 teaches that order-of-magnitude estimates often suffice for strategic choices."},
        {"difficulty": "hard", "question": "A startup estimates customer lifetime value (CLV) using averages, ignoring variance. They over-invest in acquisition. What went wrong?", "options": [{"label": "A", "text": "Estimation itself is flawed", "is_correct": False}, {"label": "B", "text": "Point estimates without uncertainty ranges led to poor decisions", "is_correct": True}, {"label": "C", "text": "CLV is irrelevant", "is_correct": False}, {"label": "D", "text": "Random bad luck", "is_correct": False}], "explanation": "FA50 emphasizes probabilistic thinking—estimates should include ranges and confidence."},
        {"difficulty": "hard", "question": "During a pandemic, epidemiologists estimate infection rates with incomplete testing data. Skeptics reject estimates as unreliable. What's the counterargument?", "options": [{"label": "A", "text": "Estimates are useless", "is_correct": False}, {"label": "B", "text": "Imperfect estimates enable timely action; waiting for perfect data causes delays", "is_correct": True}, {"label": "C", "text": "Ignore all data", "is_correct": False}, {"label": "D", "text": "Estimates are always wrong", "is_correct": False}], "explanation": "FA50 teaches balancing uncertainty with urgency—estimation is a pragmatic tool."}
    ],
    "#deduction": [
        {"difficulty": "easy", "question": "What is deductive reasoning?", "options": [{"label": "A", "text": "Drawing specific conclusions from general principles", "is_correct": True}, {"label": "B", "text": "Guessing randomly", "is_correct": False}, {"label": "C", "text": "Generalizing from observations", "is_correct": False}, {"label": "D", "text": "Ignoring logic", "is_correct": False}], "explanation": "Deduction moves from premises to logically certain conclusions."},
        {"difficulty": "easy", "question": "Which is a deductive argument?", "options": [{"label": "A", "text": "All humans are mortal; Socrates is human; therefore Socrates is mortal.", "is_correct": True}, {"label": "B", "text": "I saw three black crows; all crows are black.", "is_correct": False}, {"label": "C", "text": "It might rain tomorrow.", "is_correct": False}, {"label": "D", "text": "I feel this is true.", "is_correct": False}], "explanation": "Classic syllogism: valid deductive structure with certain conclusion."},
        {"difficulty": "medium", "question": "If all CS50 students must complete problem sets, and Jane is a CS50 student, what follows deductively?", "options": [{"label": "A", "text": "Jane might complete problem sets", "is_correct": False}, {"label": "B", "text": "Jane must complete problem sets", "is_correct": True}, {"label": "C", "text": "Jane is exempt", "is_correct": False}, {"label": "D", "text": "Nothing follows", "is_correct": False}], "explanation": "Deduction guarantees the conclusion if premises are true."},
        {"difficulty": "medium", "question": "A detective finds a suspect's fingerprint at a crime scene. Can they deductively conclude guilt?", "options": [{"label": "A", "text": "Yes, it is certain", "is_correct": False}, {"label": "B", "text": "No, deduction requires ruling out all alternatives; the fingerprint is evidence, not proof", "is_correct": True}, {"label": "C", "text": "Fingerprints are irrelevant", "is_correct": False}, {"label": "D", "text": "Deduction doesn't apply", "is_correct": False}], "explanation": "Deduction is certain only given complete premises; forensic reasoning is often probabilistic."},
        {"difficulty": "medium", "question": "A math proof shows: If a triangle has two equal sides, its base angles are equal. Given an isosceles triangle, what can you deduce?", "options": [{"label": "A", "text": "Nothing", "is_correct": False}, {"label": "B", "text": "Its base angles are equal", "is_correct": True}, {"label": "C", "text": "It might have equal angles", "is_correct": False}, {"label": "D", "text": "It is random", "is_correct": False}], "explanation": "Mathematical deduction from definitions and theorems yields certainty."},
        {"difficulty": "hard", "question": "A policy states: 'If GDP falls two consecutive quarters, the economy is in recession.' GDP falls Q1 and Q2. What can you deduce?", "options": [{"label": "A", "text": "The economy is definitely in recession by this definition", "is_correct": True}, {"label": "B", "text": "The economy might be in recession", "is_correct": False}, {"label": "C", "text": "The definition is irrelevant", "is_correct": False}, {"label": "D", "text": "Nothing follows", "is_correct": False}], "explanation": "Deduction from the definition yields a certain classification."},
        {"difficulty": "hard", "question": "A scientist says: 'If theory X is true, we should observe Y. We observe Y.' Can they deductively conclude X is true?", "options": [{"label": "A", "text": "Yes, Y proves X", "is_correct": False}, {"label": "B", "text": "No, this is affirming the consequent—a logical fallacy", "is_correct": True}, {"label": "C", "text": "Deduction doesn't apply to science", "is_correct": False}, {"label": "D", "text": "Observation is irrelevant", "is_correct": False}], "explanation": "Deduction requires valid structure; confirming a prediction supports but doesn't prove a theory."},
        {"difficulty": "hard", "question": "In formal logic, a valid deductive argument can have a false conclusion. How?", "options": [{"label": "A", "text": "If one or more premises are false", "is_correct": True}, {"label": "B", "text": "Deduction is always true", "is_correct": False}, {"label": "C", "text": "Logic is broken", "is_correct": False}, {"label": "D", "text": "Validity guarantees truth", "is_correct": False}], "explanation": "Validity concerns structure; soundness requires both valid structure and true premises."}
    ],
    "#fallacies": [
        {"difficulty": "easy", "question": "What is a logical fallacy?", "options": [{"label": "A", "text": "A valid argument", "is_correct": False}, {"label": "B", "text": "An error in reasoning that undermines an argument", "is_correct": True}, {"label": "C", "text": "A correct conclusion", "is_correct": False}, {"label": "D", "text": "A mathematical proof", "is_correct": False}], "explanation": "Fallacies are flawed reasoning patterns that appear persuasive but are invalid."},
        {"difficulty": "easy", "question": "Which is an example of ad hominem fallacy?", "options": [{"label": "A", "text": "Attacking a person's character instead of their argument", "is_correct": True}, {"label": "B", "text": "Providing evidence for a claim", "is_correct": False}, {"label": "C", "text": "Using statistics", "is_correct": False}, {"label": "D", "text": "Logical reasoning", "is_correct": False}], "explanation": "Ad hominem targets the person, not the argument's merits."},
        {"difficulty": "medium", "question": "'Everyone I know supports this policy, so it must be right.' Which fallacy is this?", "options": [{"label": "A", "text": "Straw man", "is_correct": False}, {"label": "B", "text": "Bandwagon (appeal to popularity)", "is_correct": True}, {"label": "C", "text": "False dilemma", "is_correct": False}, {"label": "D", "text": "Slippery slope", "is_correct": False}], "explanation": "Popularity doesn't establish truth—bandwagon fallacy."},
        {"difficulty": "medium", "question": "'If we allow students to redo exams, soon they'll demand infinite retakes and standards will collapse.' Which fallacy?", "options": [{"label": "A", "text": "Slippery slope", "is_correct": True}, {"label": "B", "text": "Ad hominem", "is_correct": False}, {"label": "C", "text": "Straw man", "is_correct": False}, {"label": "D", "text": "Appeal to authority", "is_correct": False}], "explanation": "Slippery slope assumes an extreme, unwarranted chain of events."},
        {"difficulty": "medium", "question": "A politician says: 'You're either with us or against us.' Which fallacy?", "options": [{"label": "A", "text": "False dilemma (false dichotomy)", "is_correct": True}, {"label": "B", "text": "Circular reasoning", "is_correct": False}, {"label": "C", "text": "Red herring", "is_correct": False}, {"label": "D", "text": "Hasty generalization", "is_correct": False}], "explanation": "False dilemma ignores middle ground and nuance."},
        {"difficulty": "hard", "question": "A company argues: 'Our product is best because it's the best-selling.' Which fallacy is embedded?", "options": [{"label": "A", "text": "Circular reasoning and appeal to popularity", "is_correct": True}, {"label": "B", "text": "Valid deduction", "is_correct": False}, {"label": "C", "text": "Ad hominem", "is_correct": False}, {"label": "D", "text": "No fallacy", "is_correct": False}], "explanation": "Sales don't prove quality; this combines circular logic and bandwagon."},
        {"difficulty": "hard", "question": "An opponent of a tax proposal misrepresents it as 'confiscating all income,' then refutes that extreme claim. Which fallacy?", "options": [{"label": "A", "text": "Straw man", "is_correct": True}, {"label": "B", "text": "Ad hominem", "is_correct": False}, {"label": "C", "text": "Appeal to emotion", "is_correct": False}, {"label": "D", "text": "False cause", "is_correct": False}], "explanation": "Straw man distorts an argument to make it easier to attack."},
        {"difficulty": "hard", "question": "A debater says: 'My opponent has no degree in economics, so their argument is invalid.' If the argument's logic is sound, which fallacy is committed?", "options": [{"label": "A", "text": "Ad hominem (attacking credentials rather than argument)", "is_correct": True}, {"label": "B", "text": "Appeal to authority", "is_correct": False}, {"label": "C", "text": "Circular reasoning", "is_correct": False}, {"label": "D", "text": "No fallacy", "is_correct": False}], "explanation": "Dismissing based on credentials rather than evaluating the argument is ad hominem."}
    ],
    "#induction": [
        {"difficulty": "easy", "question": "What is inductive reasoning?", "options": [{"label": "A", "text": "Deriving general principles from specific observations", "is_correct": True}, {"label": "B", "text": "Deducing specifics from general rules", "is_correct": False}, {"label": "C", "text": "Random guessing", "is_correct": False}, {"label": "D", "text": "Ignoring evidence", "is_correct": False}], "explanation": "Induction moves from observed patterns to broader generalizations."},
        {"difficulty": "easy", "question": "Which is an example of inductive reasoning?", "options": [{"label": "A", "text": "The sun rose every day I've observed, so it will likely rise tomorrow.", "is_correct": True}, {"label": "B", "text": "All triangles have three sides; this shape has three sides, so it's a triangle.", "is_correct": False}, {"label": "C", "text": "If P then Q; P, therefore Q.", "is_correct": False}, {"label": "D", "text": "Random speculation", "is_correct": False}], "explanation": "Induction generalizes from past observations to predict future events."},
        {"difficulty": "medium", "question": "A scientist observes that heating water always causes boiling at 100°C (at sea level). They induce a general law. What's the limitation?", "options": [{"label": "A", "text": "Induction guarantees certainty", "is_correct": False}, {"label": "B", "text": "Induction is probabilistic; future observations could differ (e.g., at altitude)", "is_correct": True}, {"label": "C", "text": "Observations are irrelevant", "is_correct": False}, {"label": "D", "text": "No limitation exists", "is_correct": False}], "explanation": "Induction is strong but not logically certain—new data can revise conclusions."},
        {"difficulty": "medium", "question": "A doctor sees five patients with symptom X who all have disease Y. They conclude X indicates Y. Which reasoning and risk?", "options": [{"label": "A", "text": "Deduction; no risk", "is_correct": False}, {"label": "B", "text": "Induction; risk of hasty generalization from small sample", "is_correct": True}, {"label": "C", "text": "Random guess", "is_correct": False}, {"label": "D", "text": "No reasoning", "is_correct": False}], "explanation": "Induction from limited data can lead to errors—sample size matters."},
        {"difficulty": "medium", "question": "A teacher notices students who attend office hours perform better. They induce: 'Office hours improve grades.' What confound might exist?", "options": [{"label": "A", "text": "Motivated students attend office hours and also study more", "is_correct": True}, {"label": "B", "text": "Induction is invalid", "is_correct": False}, {"label": "C", "text": "Grades are random", "is_correct": False}, {"label": "D", "text": "No confound", "is_correct": False}], "explanation": "Induction can mistake correlation for causation; confounders must be considered."},
        {"difficulty": "hard", "question": "Hume's problem of induction: Why should past regularities predict the future?", "options": [{"label": "A", "text": "They always do", "is_correct": False}, {"label": "B", "text": "Induction assumes uniformity of nature, which itself cannot be proven deductively", "is_correct": True}, {"label": "C", "text": "Past and future are irrelevant", "is_correct": False}, {"label": "D", "text": "Induction is deductive", "is_correct": False}], "explanation": "Hume highlighted that induction rests on an unprovable assumption—FA50 examines its limits."},
        {"difficulty": "hard", "question": "A researcher induces a theory from 100 experiments. One new experiment contradicts it. What's the FA50 lesson?", "options": [{"label": "A", "text": "Inductive conclusions are provisional; anomalies require theory revision", "is_correct": True}, {"label": "B", "text": "Ignore the anomaly", "is_correct": False}, {"label": "C", "text": "Induction guarantees truth", "is_correct": False}, {"label": "D", "text": "Discard all prior data", "is_correct": False}], "explanation": "Induction builds strong but revisable knowledge—science updates theories with new evidence."},
        {"difficulty": "hard", "question": "Machine learning models generalize from training data (induction). They fail on novel data. Which principle explains this?", "options": [{"label": "A", "text": "Inductive inference is limited by sample representativeness and overfitting", "is_correct": True}, {"label": "B", "text": "Models are perfect", "is_correct": False}, {"label": "C", "text": "Induction always succeeds", "is_correct": False}, {"label": "D", "text": "Training data is irrelevant", "is_correct": False}], "explanation": "FA50 teaches that induction quality depends on data diversity and avoiding over-generalization."}
    ]
}
