"""MC50 HC Question Bank
Structured MCQ items for every HC in the MC50 course.
Each question contains: difficulty, stem, options, correct answer flag, and explanation.
"""

MC50_HC_QUESTIONS = {
    "#connotation": [
        {"difficulty": "easy", "question": "What is connotation?", "options": [{"label": "A", "text": "The dictionary definition of a word", "is_correct": False}, {"label": "B", "text": "The emotional or cultural associations a word carries", "is_correct": True}, {"label": "C", "text": "The spelling of a word", "is_correct": False}, {"label": "D", "text": "A grammatical rule", "is_correct": False}], "explanation": "Connotation refers to implied meanings beyond the literal definition."},
        {"difficulty": "easy", "question": "Which pair shows different connotations?", "options": [{"label": "A", "text": "'Cheap' vs 'affordable'", "is_correct": True}, {"label": "B", "text": "'Dog' vs 'canine'", "is_correct": False}, {"label": "C", "text": "'Run' vs 'jog'", "is_correct": False}, {"label": "D", "text": "'Chair' vs 'seat'", "is_correct": False}], "explanation": "'Cheap' has negative connotations (low quality), 'affordable' is neutral-positive."},
        {"difficulty": "medium", "question": "A politician calls an opponent's proposal 'radical.' Why does word choice matter?", "options": [{"label": "A", "text": "It's the dictionary definition", "is_correct": False}, {"label": "B", "text": "'Radical' connotes extremism, shaping audience perception negatively", "is_correct": True}, {"label": "C", "text": "Word choice is irrelevant", "is_correct": False}, {"label": "D", "text": "All synonyms are equal", "is_correct": False}], "explanation": "Connotation influences framing and rhetorical impact—MC50 emphasizes awareness."},
        {"difficulty": "medium", "question": "A marketer chooses 'pre-owned' instead of 'used' for cars. Which MC50 concept applies?", "options": [{"label": "A", "text": "#connotation—managing emotional associations", "is_correct": True}, {"label": "B", "text": "#professionalism—formal tone", "is_correct": False}, {"label": "C", "text": "#context—situational fit", "is_correct": False}, {"label": "D", "text": "#critique—evaluating arguments", "is_correct": False}], "explanation": "'Pre-owned' has more positive connotations than 'used'."},
        {"difficulty": "medium", "question": "A journalist describes a protest as 'riot' vs 'demonstration.' How does connotation affect readers?", "options": [{"label": "A", "text": "'Riot' implies chaos/violence; 'demonstration' implies peaceful expression", "is_correct": True}, {"label": "B", "text": "No difference", "is_correct": False}, {"label": "C", "text": "Only denotation matters", "is_correct": False}, {"label": "D", "text": "Readers ignore word choice", "is_correct": False}], "explanation": "Connotation shapes narrative framing and audience interpretation."},
        {"difficulty": "hard", "question": "A company rebrands 'layoffs' as 'rightsizing.' Critics call this euphemism manipulative. What's the MC50 analysis?", "options": [{"label": "A", "text": "Euphemisms exploit connotation to soften negative realities, raising ethical questions", "is_correct": True}, {"label": "B", "text": "Connotation is irrelevant", "is_correct": False}, {"label": "C", "text": "All word choices are neutral", "is_correct": False}, {"label": "D", "text": "Rebranding is always deceptive", "is_correct": False}], "explanation": "MC50 teaches critical awareness of how connotation can obscure or manipulate."},
        {"difficulty": "hard", "question": "A historian writes about 'freedom fighters' vs 'terrorists' for the same group. Which principle is at stake?", "options": [{"label": "A", "text": "Denotation only", "is_correct": False}, {"label": "B", "text": "Connotation reflects perspective and bias; word choice is never neutral", "is_correct": True}, {"label": "C", "text": "Grammar rules", "is_correct": False}, {"label": "D", "text": "No principle", "is_correct": False}], "explanation": "Connotation reveals ideological stance—MC50 emphasizes reflective language use."},
        {"difficulty": "hard", "question": "A legal brief uses 'terminate' instead of 'kill' in a case. Opposing counsel objects that connotation minimizes severity. What's the debate?", "options": [{"label": "A", "text": "Whether connotative framing unduly influences jurors", "is_correct": True}, {"label": "B", "text": "Denotation is the only concern", "is_correct": False}, {"label": "C", "text": "Word choice doesn't matter in law", "is_correct": False}, {"label": "D", "text": "Synonyms are identical", "is_correct": False}], "explanation": "MC50 highlights how connotation impacts persuasion and fairness in communication."}
    ],
    "#professionalism": [
        {"difficulty": "easy", "question": "What does professionalism in communication involve?", "options": [{"label": "A", "text": "Using slang and informal language", "is_correct": False}, {"label": "B", "text": "Adapting tone, style, and formality to context and audience", "is_correct": True}, {"label": "C", "text": "Ignoring audience expectations", "is_correct": False}, {"label": "D", "text": "Being overly casual", "is_correct": False}], "explanation": "Professionalism means calibrating communication to situation and audience."},
        {"difficulty": "easy", "question": "Which email greeting is most professional for a job application?", "options": [{"label": "A", "text": "'Hey!'", "is_correct": False}, {"label": "B", "text": "'Dear Hiring Manager,'", "is_correct": True}, {"label": "C", "text": "'Yo,'", "is_correct": False}, {"label": "D", "text": "'Sup?'", "is_correct": False}], "explanation": "Formal contexts demand formal greetings—MC50 teaches situational appropriateness."},
        {"difficulty": "medium", "question": "A student emails a professor: 'yo can u send me the notes lol'. What's the issue?", "options": [{"label": "A", "text": "Perfect professional tone", "is_correct": False}, {"label": "B", "text": "Tone is too informal; lacks respect and professionalism for academic context", "is_correct": True}, {"label": "C", "text": "Email is outdated", "is_correct": False}, {"label": "D", "text": "No issue", "is_correct": False}], "explanation": "Professionalism requires recognizing power dynamics and norms."},
        {"difficulty": "medium", "question": "In a Slack channel with colleagues, casual tone is fine. In a board presentation, formal tone is needed. Which MC50 HC explains this?", "options": [{"label": "A", "text": "#professionalism—adapting register to audience and context", "is_correct": True}, {"label": "B", "text": "#connotation—word associations", "is_correct": False}, {"label": "C", "text": "#critique—evaluating arguments", "is_correct": False}, {"label": "D", "text": "#interpretivelens—perspective", "is_correct": False}], "explanation": "Professionalism is context-dependent flexibility."},
        {"difficulty": "medium", "question": "A doctor explains a diagnosis using jargon patients don't understand. What's lacking?", "options": [{"label": "A", "text": "Technical knowledge", "is_correct": False}, {"label": "B", "text": "Audience-appropriate communication (professionalism)", "is_correct": True}, {"label": "C", "text": "Medical accuracy", "is_correct": False}, {"label": "D", "text": "Nothing", "is_correct": False}], "explanation": "Professionalism includes clarity and accessibility for your audience."},
        {"difficulty": "hard", "question": "A junior employee challenges a senior leader's idea in a public meeting with blunt language. The idea is flawed, but colleagues are uncomfortable. What's the MC50 lesson?", "options": [{"label": "A", "text": "Content was correct, so delivery doesn't matter", "is_correct": False}, {"label": "B", "text": "Professionalism balances honesty with tact and hierarchy awareness", "is_correct": True}, {"label": "C", "text": "Never challenge superiors", "is_correct": False}, {"label": "D", "text": "Formality is oppressive", "is_correct": False}], "explanation": "Effective critique requires professional framing to be heard and respected."},
        {"difficulty": "hard", "question": "A company's internal culture is casual, but they lose a client pitch because their deck used informal language. What went wrong?", "options": [{"label": "A", "text": "They failed to adapt professional register to external stakeholder expectations", "is_correct": True}, {"label": "B", "text": "Casual language is always best", "is_correct": False}, {"label": "C", "text": "Clients are unreasonable", "is_correct": False}, {"label": "D", "text": "Professionalism is irrelevant in business", "is_correct": False}], "explanation": "MC50 teaches code-switching—professionalism varies by audience and stakes."},
        {"difficulty": "hard", "question": "A researcher's grant proposal is scientifically sound but written in dense jargon. Reviewers reject it for lack of clarity. Which MC50 principle applies?", "options": [{"label": "A", "text": "#professionalism—communicating accessibly even in expert contexts", "is_correct": True}, {"label": "B", "text": "#connotation—word choice", "is_correct": False}, {"label": "C", "text": "#context—situational factors", "is_correct": False}, {"label": "D", "text": "Science doesn't require clear writing", "is_correct": False}], "explanation": "Professional writing serves the audience's needs, not just the writer's expertise."}
    ],
    "#context": [
        {"difficulty": "easy", "question": "Why does context matter in communication?", "options": [{"label": "A", "text": "It doesn't—words mean the same everywhere", "is_correct": False}, {"label": "B", "text": "Context shapes how messages are interpreted", "is_correct": True}, {"label": "C", "text": "Context is irrelevant", "is_correct": False}, {"label": "D", "text": "Only grammar matters", "is_correct": False}], "explanation": "MC50 teaches that meaning is co-constructed by text and context."},
        {"difficulty": "easy", "question": "The phrase 'That's sick!' can mean 'awesome' or 'disgusting.' What determines the meaning?", "options": [{"label": "A", "text": "The dictionary", "is_correct": False}, {"label": "B", "text": "The social context and tone", "is_correct": True}, {"label": "C", "text": "Nothing", "is_correct": False}, {"label": "D", "text": "Random chance", "is_correct": False}], "explanation": "Context disambiguates meaning—slang interpretation depends on setting."},
        {"difficulty": "medium", "question": "A joke appropriate among friends offends in a work meeting. Which MC50 HC explains this?", "options": [{"label": "A", "text": "#context—audience and setting shift appropriateness", "is_correct": True}, {"label": "B", "text": "#connotation—word choice", "is_correct": False}, {"label": "C", "text": "#professionalism—formality alone", "is_correct": False}, {"label": "D", "text": "Jokes are universally fine", "is_correct": False}], "explanation": "Context governs what's acceptable; same content, different reception."},
        {"difficulty": "medium", "question": "A meme spreads online but its original satirical context is lost. People take it literally and spread misinformation. What happened?", "options": [{"label": "A", "text": "Decontextualization changes meaning", "is_correct": True}, {"label": "B", "text": "Memes are meaningless", "is_correct": False}, {"label": "C", "text": "Context is irrelevant", "is_correct": False}, {"label": "D", "text": "Nothing important", "is_correct": False}], "explanation": "Removing context alters interpretation—MC50 emphasizes contextual literacy."},
        {"difficulty": "medium", "question": "A historian quotes a historical figure out of context to support a modern argument. Critics call this misleading. Why?", "options": [{"label": "A", "text": "Historical context is essential for accurate interpretation", "is_correct": True}, {"label": "B", "text": "Quotes mean the same in any era", "is_correct": False}, {"label": "C", "text": "Context doesn't matter", "is_correct": False}, {"label": "D", "text": "History is irrelevant", "is_correct": False}], "explanation": "MC50 teaches that stripping context distorts meaning and can mislead."},
        {"difficulty": "hard", "question": "A news outlet publishes a politician's quote: 'I support violence.' The full sentence was: 'I don't support violence.' What's the ethical issue?", "options": [{"label": "A", "text": "Selective quoting (decontextualization) misrepresents intent", "is_correct": True}, {"label": "B", "text": "Quotes are always fair game", "is_correct": False}, {"label": "C", "text": "Context is optional", "is_correct": False}, {"label": "D", "text": "No ethical issue", "is_correct": False}], "explanation": "MC50 emphasizes responsible communication requires preserving context."},
        {"difficulty": "hard", "question": "A Supreme Court decision is cited by both sides of a debate, each emphasizing different passages. Which MC50 concept explains this?", "options": [{"label": "A", "text": "#context and #interpretivelens—framing and selection shape meaning", "is_correct": True}, {"label": "B", "text": "#connotation—word choice alone", "is_correct": False}, {"label": "C", "text": "Legal texts have one meaning", "is_correct": False}, {"label": "D", "text": "Context is irrelevant in law", "is_correct": False}], "explanation": "Context and interpretive lens together determine how texts are read and applied."},
        {"difficulty": "hard", "question": "A company's apology statement is read as sincere by supporters and insincere by critics, despite identical wording. What explains divergent interpretations?", "options": [{"label": "A", "text": "Audience context (prior beliefs, trust) shapes reception", "is_correct": True}, {"label": "B", "text": "Words have fixed meanings", "is_correct": False}, {"label": "C", "text": "One group is wrong", "is_correct": False}, {"label": "D", "text": "Random variation", "is_correct": False}], "explanation": "MC50 teaches that meaning emerges from interaction of text, context, and audience."}
    ],
    "#critique": [
        {"difficulty": "easy", "question": "What is constructive critique?", "options": [{"label": "A", "text": "Tearing down ideas without alternatives", "is_correct": False}, {"label": "B", "text": "Evaluating strengths and weaknesses to improve understanding or work", "is_correct": True}, {"label": "C", "text": "Praising everything uncritically", "is_correct": False}, {"label": "D", "text": "Ignoring flaws", "is_correct": False}], "explanation": "Critique in MC50 means thoughtful evaluation, not mere negativity."},
        {"difficulty": "easy", "question": "Which is an example of constructive critique?", "options": [{"label": "A", "text": "'This essay is terrible.'", "is_correct": False}, {"label": "B", "text": "'The thesis is clear, but evidence in paragraph 3 is weak; consider adding data.'", "is_correct": True}, {"label": "C", "text": "'I love everything.'", "is_correct": False}, {"label": "D", "text": "No feedback", "is_correct": False}], "explanation": "Constructive critique identifies issues and suggests improvements."},
        {"difficulty": "medium", "question": "A peer review says: 'Your argument is illogical and stupid.' What's missing?", "options": [{"label": "A", "text": "Nothing—critique is fine", "is_correct": False}, {"label": "B", "text": "Specificity, evidence, and respectful tone", "is_correct": True}, {"label": "C", "text": "More negativity", "is_correct": False}, {"label": "D", "text": "Praise", "is_correct": False}], "explanation": "Effective critique in MC50 is specific, evidence-based, and respectful."},
        {"difficulty": "medium", "question": "A designer receives feedback: 'This layout is confusing because key info is buried; try highlighting it.' Which MC50 HC is demonstrated?", "options": [{"label": "A", "text": "#critique—offering actionable, specific evaluation", "is_correct": True}, {"label": "B", "text": "#connotation—word choice", "is_correct": False}, {"label": "C", "text": "#context—situational factors", "is_correct": False}, {"label": "D", "text": "No HC", "is_correct": False}], "explanation": "This is constructive critique: identifying problem and suggesting solution."},
        {"difficulty": "medium", "question": "A student dismisses all criticism with 'That's just your opinion.' What's the issue?", "options": [{"label": "A", "text": "Rejecting critique without engaging its substance", "is_correct": True}, {"label": "B", "text": "Perfect response", "is_correct": False}, {"label": "C", "text": "Critique is always subjective", "is_correct": False}, {"label": "D", "text": "No issue", "is_correct": False}], "explanation": "MC50 teaches engaging critique seriously, distinguishing subjective preference from reasoned evaluation."},
        {"difficulty": "hard", "question": "A paper receives critique: 'Your methodology is flawed.' The author improves methods and thanks the reviewer. What does this model?", "options": [{"label": "A", "text": "Intellectual humility and using critique for growth", "is_correct": True}, {"label": "B", "text": "Weakness", "is_correct": False}, {"label": "C", "text": "Avoiding critique", "is_correct": False}, {"label": "D", "text": "Random luck", "is_correct": False}], "explanation": "MC50 emphasizes critique as a tool for refinement, not personal attack."},
        {"difficulty": "hard", "question": "A film critic's review balances praise (cinematography) with criticism (weak plot). Fans accuse them of bias. What's the MC50 perspective?", "options": [{"label": "A", "text": "Balanced critique acknowledging both strengths and weaknesses is rigorous, not biased", "is_correct": True}, {"label": "B", "text": "Critique should only praise", "is_correct": False}, {"label": "C", "text": "Critique is inherently negative", "is_correct": False}, {"label": "D", "text": "Critics are always wrong", "is_correct": False}], "explanation": "MC50 teaches nuanced critique—recognizing both merits and flaws."},
        {"difficulty": "hard", "question": "An academic peer review rejects a paper not for being wrong but for lacking novelty. The author complains this isn't 'real critique.' What's the rebuttal?", "options": [{"label": "A", "text": "Critique includes evaluating contribution and significance, not just correctness", "is_correct": True}, {"label": "B", "text": "Only factual errors matter", "is_correct": False}, {"label": "C", "text": "Novelty is irrelevant", "is_correct": False}, {"label": "D", "text": "Rejection is unfair", "is_correct": False}], "explanation": "MC50 frames critique as multidimensional—validity, relevance, originality, and impact all matter."}
    ],
    "#interpretivelens": [
        {"difficulty": "easy", "question": "What is an interpretive lens?", "options": [{"label": "A", "text": "A physical magnifying glass", "is_correct": False}, {"label": "B", "text": "A framework or perspective that shapes how you read and understand texts", "is_correct": True}, {"label": "C", "text": "A random opinion", "is_correct": False}, {"label": "D", "text": "A grammatical rule", "is_correct": False}], "explanation": "Interpretive lenses (e.g., feminist, historical, economic) guide analysis."},
        {"difficulty": "easy", "question": "Reading a novel through a feminist lens means:", "options": [{"label": "A", "text": "Ignoring the text", "is_correct": False}, {"label": "B", "text": "Analyzing gender roles, power, and representation", "is_correct": True}, {"label": "C", "text": "Memorizing the plot", "is_correct": False}, {"label": "D", "text": "Disliking the book", "is_correct": False}], "explanation": "A feminist lens focuses on gender dynamics—MC50 teaches multiple interpretive approaches."},
        {"difficulty": "medium", "question": "Two readers interpret the same poem differently: one sees hope, another despair. Which MC50 principle applies?", "options": [{"label": "A", "text": "One reader is wrong", "is_correct": False}, {"label": "B", "text": "Interpretive lenses and personal context shape meaning", "is_correct": True}, {"label": "C", "text": "Poetry is meaningless", "is_correct": False}, {"label": "D", "text": "Only the author's intent matters", "is_correct": False}], "explanation": "MC50 teaches that interpretation is influenced by the lens and context readers bring."},
        {"difficulty": "medium", "question": "A historian analyzes a war through an economic lens (resource competition) vs a nationalist lens (identity conflict). What does this show?", "options": [{"label": "A", "text": "Different lenses reveal different dimensions of the same event", "is_correct": True}, {"label": "B", "text": "One lens is correct", "is_correct": False}, {"label": "C", "text": "Lenses are irrelevant", "is_correct": False}, {"label": "D", "text": "History has one interpretation", "is_correct": False}], "explanation": "MC50 emphasizes that interpretive lenses highlight different aspects; no single lens is complete."},
        {"difficulty": "medium", "question": "A student writes: 'The author clearly meant X.' The professor asks: 'What lens are you using?' Why?", "options": [{"label": "A", "text": "To encourage awareness that interpretations depend on perspective", "is_correct": True}, {"label": "B", "text": "To confuse the student", "is_correct": False}, {"label": "C", "text": "Meaning is always obvious", "is_correct": False}, {"label": "D", "text": "No reason", "is_correct": False}], "explanation": "MC50 teaches reflective reading—recognizing your interpretive stance."},
        {"difficulty": "hard", "question": "A legal scholar applies originalist vs living-document lenses to the Constitution. Critics say one is wrong. What's the MC50 take?", "options": [{"label": "A", "text": "Both are coherent lenses with different premises; debate hinges on which lens is more justified", "is_correct": True}, {"label": "B", "text": "Only one lens is valid", "is_correct": False}, {"label": "C", "text": "Lenses are arbitrary", "is_correct": False}, {"label": "D", "text": "Interpretation doesn't matter", "is_correct": False}], "explanation": "MC50 recognizes interpretive pluralism—lenses are tools, each with trade-offs."},
        {"difficulty": "hard", "question": "A postcolonial lens reveals power dynamics in a classic novel that a formalist lens (focused on structure) overlooks. What does this illustrate?", "options": [{"label": "A", "text": "Lenses uncover different insights; combining lenses enriches understanding", "is_correct": True}, {"label": "B", "text": "One lens is superior", "is_correct": False}, {"label": "C", "text": "Only one reading is correct", "is_correct": False}, {"label": "D", "text": "Lenses are useless", "is_correct": False}], "explanation": "MC50 teaches that multiple lenses offer complementary perspectives."},
        {"difficulty": "hard", "question": "A critic applies a psychoanalytic lens to a film, seeing unconscious desires. Audiences reject this as over-interpretation. What's the debate?", "options": [{"label": "A", "text": "Whether the lens is appropriately grounded in textual evidence or speculative", "is_correct": True}, {"label": "B", "text": "Lenses are always valid", "is_correct": False}, {"label": "C", "text": "Interpretation is purely subjective", "is_correct": False}, {"label": "D", "text": "Psychoanalysis is inherently wrong", "is_correct": False}], "explanation": "MC50 emphasizes that lenses must be applied rigorously with evidence, not arbitrarily."}
    ]
}
